solution TextTagger using a regex
what-a-fix/pure-php-test-skills pull request #2
Opened 2020-11-14 10:26 UTC by Florian-Rowehy

2020-11-14 14:54 UTC, MockingMagician commented
Bonjour @Florian-Rowehy 

Je viens de t'écrire un mail. Je n'avais pas encore vu ta PR, je vais en prendre connaissance dès maintenant :smile:

2020-11-14 16:42 UTC, MockingMagician requested changes
@Florian-Rowehy 
Jolie PR pour une première PR du projet :+1: 
Bon je n'ai que lu ton code, pas testé. Je le ferai ce soir si j'ai un moment.

2020-11-14 16:42 UTC, MockingMagician commented on src/TextTagger.php
> +{
Attention au CS (code style) ça ne change pas le fonctionnement mais c'est bien de respecter les usages.
```suggestion
<?php

namespace Whatafix\TextTagger;

use Whatafix\TextTagger\Contracts\TextTaggerInterface;

class TextTagger implements TextTaggerInterface
{

```

2020-11-14 16:42 UTC, MockingMagician commented on src/TextTagger.php
> +        $tags = array();
:+1: Bien si le foreach ne ressort pas de tag on aura un array vide, parfait.

Préfère une short syntax pour les array :

```suggestion
        $tags = [];

```

2020-11-14 16:42 UTC, MockingMagician commented on tests/TextTaggerTest.php
> +    }
Regarde le code de la class que tu étends => TestCase. Tu pourras y voir le commentaire @internal, il n'est pas conseillé d'étendre le constructeur de TestCase.

Pour initier tes variables de test, phpunit fourni la méthode setUp()

2020-11-14 16:42 UTC, MockingMagician commented on tests/TextTaggerTest.php
> +    }
Je ne suis pas sur que cela soit très pertinent de tester que tu es sur la bonne instance d'objet puisque tu es censé tester cet objet et que tu l'initialise, je ne vois même pas dans quel cas ce test serait en mesure d'échouer.

2020-11-14 16:42 UTC, MockingMagician commented on tests/TextTaggerTest.php
> +        $this->assertTrue(empty(array_diff(["family", "walk"], $tags)));
je pense que assertEquals devrait faire l'affaire
```suggestion
        $this->assertEquals(["family", "walk"], $tags);
```

2020-11-14 16:42 UTC, MockingMagician commented on tests/TextTaggerTest.php
> +        $this->assertEquals(1,sizeof($tags));
assertCount devrait faire l'affaire
```suggestion
        $this->assertCount(1, $tags);
```

2020-11-14 16:42 UTC, MockingMagician commented on tests/TextTaggerTest.php
> +        $this->assertEquals(1,sizeof($tags));
Idem

2020-11-14 16:42 UTC, MockingMagician commented on tests/TextTaggerTest.php
> +        $this->assertTrue(empty(array_diff(["family", "walk", "bathroom", "school"], $tags)));
idem assertEquals devrait faire l'affaire

2020-11-14 16:42 UTC, MockingMagician commented on tests/TextTaggerTest.php
> +        $this->assertTrue(empty(array_diff(["family", "walk", "bathroom", "school"], $tags)));
idem assertEquals devrait faire l'affaire

2020-11-14 16:42 UTC, MockingMagician commented on tests/TextTaggerTest.php
> +    }*/
Ne laisse pas de code commenté où justifie avec un TODO. example: TODO implémenter blabla... ne pas effacer ce code....

2020-11-14 16:42 UTC, MockingMagician commented on tests/TextTaggerTest.php
> +        $this->assertTrue(["train"]==$tags);
assertEquals

2020-11-14 16:42 UTC, MockingMagician commented on tests/TextTaggerTest.php
> +        $this->assertTrue(["school"]==$tags);
assertEquals

2020-11-14 16:42 UTC, MockingMagician commented on tests/TextTaggerTest.php
> +        $this->assertEquals(1,sizeof($tags));
assertCount

2020-11-14 16:42 UTC, MockingMagician commented on tests/TextTaggerTest.php
> +        $this->assertTrue(empty($tags));
assertEmpty

2020-11-14 16:42 UTC, MockingMagician commented on tests/TextTaggerTest.php
> +        $this->assertTrue($diffTime<=6);
Si tu veut faire un benchmark, il faut s'y prendre d'une autre façon et en général on ne mélange pas avec les tests unitaires.

Surtout que $this->assertTrue($diffTime<=6); ça dépend de ma machine, dison que si je le fait depuis un ordi avec un tout petit processeur qui est bien occupé avec des taches de fond (même un gros processeur, s'il est vraiment très occupé) et bien ton test échouera.

Un bench en soit ça n'échoue pas ça donne des stats en fonction d'une machine et d'un environement

2020-11-14 16:44 UTC, MockingMagician requested changes

2020-11-14 16:44 UTC, MockingMagician commented on composer.json
> +            "Whatafix\\TextTagger\\Test\\": "tests/"
Bien mais déplace le dans autoload-dev

2020-11-14 17:48 UTC, Florian-Rowehy commented
Merci Mr. MOREAU pour tous vos retours,  j'ai réalisé les changements et j'en ai profité pour ajouter 2 fonctionnalités, la 1e est la détection d'un mot qui se répète (j'avais oublié de le prendre en compte), la 2e il faut au minimum de 2 mots d'un même label pour que celui soit ajouté. Je vais me pencher sur les fichiers config de thèmes  😄

2020-11-14 18:22 UTC, Florian-Rowehy commented
J'ai ajouté le chargement de fichier, pour que cela retourne un tableau directement, j'ai utilisé la méthode include pour récupérer le tableau à 2 niveaux. 
Une autre possibilité aurait été de créer un fichier pour chaque label et utiliser la fonction file pour transformer le fichier text en tableau.

2020-11-14 19:14 UTC, MockingMagician requested changes
C'est top !

2020-11-14 19:14 UTC, MockingMagician commented on composer.json
> +        }
:+1:

2020-11-14 19:14 UTC, MockingMagician commented on src/label/label.php
> +];
EOL absent

2020-11-14 19:14 UTC, MockingMagician commented on src/TextTagger.php
> +    }
Ok c'est pas mal, mais il va falloir tester ce qui se passe quand le fichier n’existe pas et voir aussi si la valeur de tagList est toujours un array...

2020-11-14 19:14 UTC, MockingMagician commented on src/TextTagger.php
> +                if ($countMatch>1) {
L'idée avec ça c'est qu'il y ai une répétition de mots clef pour renforcer l'appartenance au TAG ?

2020-11-14 19:14 UTC, MockingMagician commented on src/TextTagger.php
> +        $this->tagList = include __DIR__ . '/label/' . $fileName;
il vaudrait mieux un full path. Pourquoi ?
Disons que j'importe cette librairie dans un projet, et que je rajoute des fichiers de thème, et bien je vais me retrouver à être obligé de les mettres dans le dossier label de la librarie qui se trouvera être dans le dossier vendor... hors le vendor n'est pas versionné donc en dehors du scope de mon projet

2020-11-14 20:09 UTC, MockingMagician commented
@Florian-Rowehy 

J'ai testé ton code en local, parfait. Disons maintenant que je veuille faire appel à la méthode public function fetchTagList(string $fileName): void

ou plutôt que je voudrais renommer addThemeTags(string $filePath): void pour que je puisse tagger en important plusieurs fichier de thème...

example :

```php
$tagger = new TextTagger();
$tagger->addThemeTags('path/to/theme/natural');
$tagger->addThemeTags('path/to/theme/family');

$tagger->getTags($someText);
```

2020-11-15 06:08 UTC, Florian-Rowehy commented on src/TextTagger.php
> +                if ($countMatch>1) {
Oui tout à fait, au minimum 2 mots.
Nous pouvons même rendre le nombre de détection minimal dynamique. 
Lorsqu'une personne appelle la méthode getTags, nous pouvons faire en sorte qu'elle aie un paramètre $minRepetition=1 comme ça l'utilisateur peut choisir à partir de combien de répétition le label est détecté
```php
public function getTags(string $text, int $minRepetition=1): array

if ($countMatch>$minRepetition) {
  $tags[] = $tag;
  break;
}
```

2020-11-15 07:08 UTC, Florian-Rowehy commented on src/TextTagger.php
> +                if ($countMatch>1) {
Au final j'ai utilisé une variable d'instance et j'ai ajouté un setter.

2020-11-15 07:15 UTC, Florian-Rowehy commented on src/TextTagger.php
> +        $this->tagList = include __DIR__ . '/label/' . $fileName;
Le full path correspond au path à partir de la racine du projet ou celui de la machine?

2020-11-15 09:40 UTC, Florian-Rowehy commented
@MockingMagician
La méthode assertEquals  lors de la comparaison des tableaux recherche une strict égalité des tableaux, l'ordre est important.
Comme j'ai eu des résultats différents en fonction de l'ordre d'addition des labels, j'ai du réutiliser la fonction array_diff à 2 endroits dans les tests. ^^

J'en ai aussi profité pour rendre le nombre de match par label dynamique. L'utilisateur peut modifier le valeur limite à l'aide d'un setter.

2020-11-15 13:40 UTC, MockingMagician commented
Hello @Florian-Rowehy 

J'ai poussé un bout de code en réponse à ton dernier message

> @MockingMagician
> La méthode assertEquals lors de la comparaison des tableaux recherche une strict égalité des tableaux, l'ordre est important.
> Comme j'ai eu des résultats différents en fonction de l'ordre d'addition des labels, j'ai du réutiliser la fonction array_diff à 2 endroits dans les tests. ^^

Il vaut mieux étendre le TestCase et créer tes propres assertions qui pourront être réutiliser dans d'autres tests. regarde les modifs que j'ai apporté.

> J'en ai aussi profité pour rendre le nombre de match par label dynamique. L'utilisateur peut modifier le valeur limite à l'aide d'un setter.

C'est une façon de faire effectivement, si le projet était réel on en discuterai certainement de façon plus poussée. Du coup je valide ta perception en l'état.

> Une possibilité d'amélioration de la method addThemeTags serait d'accepter n'importe quel fichier text et de parser l'ensemble de son contenu en tableau.

Idem qu'au dessus... Mais si on voudrait pousser au bout, je ne validerais pas ces fichiers de theme comme du PHP pur, je verrais plutôt un fichier structuré, soit JSON, soit XML, soit yaml, afin qu'on puisse parser la structure et vérifier quelle comporte les éléments attendus. Donc en amont on discuterait de la structure attendue de ce fichier, et on testerai que l'import est corret à la structure attendue.

Cela dit si tu le souhaite on peu en discuter et pousser dans ce sens...

> Nous pourrions aussi vérifier que le fichier aie le bon MIME text/x-php ou text/plain.

Du coup vérifier le mime-type n'aurait plus de sens si on part sur un fichier structuré, puisqu'on vérifierai directement sa structure...

2020-11-15 14:32 UTC, Florian-Rowehy commented
@MockingMagician 
Bonjour Mr. MOREAU
Merci pour vos retours, je suis entrain de regarder vos tests.
N'ayant jamais manipulé phpunit auparavant je ne suis pas encore très à l'aise avec. 
Je vais explorer la librairie pour mieux comprendre son fonctionnement.

Trouvant cet exercice intéressant et formateur, je souhaiterai en effet le continuer et voir où cela nous mène. 😄

2020-11-15 16:07 UTC, MockingMagician commented
> @MockingMagician
> Bonjour Mr. MOREAU
> Merci pour vos retours, je suis entrain de regarder vos tests.
> N'ayant jamais manipulé phpunit auparavant je ne suis pas encore très à l'aise avec.
> Je vais explorer la librairie pour mieux comprendre son fonctionnement.
> 
> Trouvant cet exercice intéressant et formateur, je souhaiterai en effet le continuer et voir où cela nous mène.

On sent la passion du codeur fou, ça fait plaisir  :heart:

Si tu veut aller plus loin on va déjà normaliser le projet.

Es-ce que tu connais https://github.com/FriendsOfPHP/PHP-CS-Fixer et https://github.com/phpstan/phpstan. Le premier sert à normer le code style, pour que ce soit cohérent entre tout les dev et à travers tous le projet, le deuxième permet d'analyser statiquement ton code pour y trouver des coquilles.

Commence par installer (en dev => require --dev) ces deux paquets, si besoin d'aide ping moi

2020-11-15 17:04 UTC, Florian-Rowehy commented
@MockingMagician 
Haha complétement, c'est d'ailleurs parfois problématique je passe mon temps libre à ça comme vous pouvez le remarquer ^^' 
J'ai un peu d'expérience avec phpstan, notre prof l'a installé sur nos projets pour vérifier nos commits.
Nous utilisons autre chose que php-cs-fixer mais je vois ce qu'il fait.
J'ai installé les 2 librairies et fait une passe, ils ont l'air de fonctionner correctement. 😄 
Ensuite je les ai pas configurés pour vérifier lorsque je commit

2020-11-15 17:38 UTC, MockingMagician commented
@Florian-Rowehy du coup j'ai rajouté le fichier de config pour phpcs histoire qu'il fonctionne comme on l'entend et j'ai rjouté des scripts dans le composer.json

Tu peux donc lancer les commandes 

> composer tests

Qui lance les tests unitaires

> composer phpstan

Qui lance l'analyse statique

> composer php-cs-fix

Qui fixe le code style

> composer php-cs-dry-run

Qui vérifie que le code style est fixé

> composer tests-pipe

Qui lance à la suite les tests, phpstan, et vérifie si le code style est ok

:smile:

2020-11-15 17:41 UTC, MockingMagician commented
> Ensuite je les ai pas configurés pour vérifier lorsque je commit

Veux-tu mettre en place de l'intégration continue ? Via une github action qui fera en sorte de lancer les tests et vérifier le cs à chaque commit ?

2020-11-15 18:29 UTC, Florian-Rowehy commented
@MockingMagician Peut être que nous pouvons faire comme dans votre entreprise? ça sera une sorte de mise en situation 😄

2020-11-15 19:58 UTC, MockingMagician commented
@Florian-Rowehy 

Voilà je t'ai setté un workflow qui joue la série de tests à chaque commit. Du coup si les tests ne passe pas, c'est directement inscrit dans la PR. Et le commit signalé par une croix rouge.

![Capture d’écran de 2020-11-15 20-54-09](https://user-images.githubusercontent.com/33423809/99195228-c3dae100-2784-11eb-929a-a686b2151d9c.png)

Pour ce qui est de la tournure à donner au projet, des discussions autour je te propose qu'on en reparle. Je risque de ne pas être dispo demain mais Mardi devrait être un peu plus flex, j'aurais certainement le temps d'échanger avec toi.

En attendant tu peux juste prendre le temps de réfléchir ou de coder et faire des propositions. C'est ta toile l'artiste :wink:

2020-11-16 05:25 UTC, Florian-Rowehy commented
@MockingMagician 
Bonjour Mr MOREAU,
Demain j'ai une évaluation de compétences toute la matinée et un livecoding l'après midi (cela devrait finir vers 16h). Jeudi et Vendredi je serai en hackathon.
Souhaitant être pleinement disponible pour notre entretien, je vous propose d'échanger en fin d'après midi/début de soirée?

>Une possibilité d'amélioration de la method addThemeTags serait d'accepter n'importe quel fichier text et de parser l'ensemble de son contenu en tableau.

>Idem qu'au dessus... Mais si on voudrait pousser au bout, je ne validerais pas ces fichiers de theme comme du PHP pur, je >verrais plutôt un fichier structuré, soit JSON, soit XML, soit yaml, afin qu'on puisse parser la structure et vérifier quelle >comporte les éléments attendus. Donc en amont on discuterait de la structure attendue de ce fichier, et on testerai que >l'import est corret à la structure attendue.

L'idée d'utiliser des fichiers avec du XML ou JSON me plait beaucoup. N'ayant jamais fait cela en PHP, je vais commencer à me pencher dessus. 😄

2020-11-16 07:53 UTC, MockingMagician commented
> Je viens de regarder le log des erreurs. Je me pose la question si le chargement des labels ne fonctionne pas. J'ai lancé phpunit en local, tous les tests passent, par contre j'ai les mêmes erreurs en supprimant le chargement de ceux-ci.

Fixé, ton path doit être relatif au fichier pour qu'il marche depuis n'importe quelle machine

2020-11-16 07:54 UTC, MockingMagician approved these changes

2020-11-17 08:06 UTC, Florian-Rowehy commented
@MockingMagician 
Bonjour Mr MOREAU, 
Souhaitez vous que nous prenions du temps en fin de journée pour échanger un peu ?

2020-11-17 13:00 UTC, MockingMagician commented
> @MockingMagician
> Bonjour Mr MOREAU,
> Souhaitez vous que nous prenions du temps en fin de journée pour échanger un peu ?

@Florian-Rowehy un créneau entre 17h30 et 18h serait parfait de mon côté, es-ce que cela te conviendrai ?

2020-11-17 13:24 UTC, Florian-Rowehy commented
@MockingMagician 
Cela me convient parfaitement 😄

2020-11-17 15:54 UTC, MockingMagician commented
> @MockingMagician
> Cela me convient parfaitement

Mon numéro est en signature de mon mail, tu peux m'appeler directement

2020-11-23 17:49 UTC, Florian-Rowehy commented
@MockingMagician 
Bonjour Mr MOREAU
J'ai réfléchi ce week end sur les possibles évolutions du TextTagger. 
Voici quelques idées:
* un mode pour parcourir un texte par phrase, il donnera un label au texte fonction de la proportion de phrases ayant ces labels.
* la possibilité de recevoir un document directement et le labelliser

2020-11-25 08:05 UTC, MockingMagician commented
Bonjour @Florian-Rowehy 

Du coût comme promis, j'ai aussi réfléchi un peu à la situation. Pour pousser un peu plus loin il faut commencer par normer et mathématiser un peu l'ensemble. Il existe un modèle assez bien établi dans le secteur de la recherche d'information, il s'agit du [modèle booléen étendu](https://fr.wikipedia.org/wiki/Mod%C3%A8le_bool%C3%A9en#Mod%C3%A8le_%C3%A9tendu)

Il faut s'intéresser à la version lorsque p=1 qui correspond au modèle vectoriel bien plus stable et qui pour le coût à aussi l'avantage pour nous de simplifier l'équation au maximum, les racines carrées et les puissance disparaissant.

Tu remarqueras le W dans qui représente le poid des termes recherchés, cela correspond à une pondération lorsque le terme existe qui est calculé et possède une valeur plutôt qu'un 0 ou 1 pour existe, n'existe pas. Le détail des calculs n'est pas très compliqué en soit, tu peux les retrouver [ici](https://fr.wikipedia.org/wiki/TF-IDF)

Etant donné que cette méthode est utilisée pour faire ressortir un document en fonction de thermes recherchés, elle correspond quasiment à notre besoin, nous devrions être amené à en redessiner les contours, notamment en intégration des poids arbitraires supplémentaires qui devront être défini dans les fichiers de config d'un thème pour contre balancer le fait que tous les termes ne sont pas forcément souhaités ou n'ont pas forcément la pertinence demandée, voir sont contre pertinent.

Je te laisse digérer l'info, ne prend pas peur, ce sont vraiment des équations très simples, j'essaierai de te poser un premier jet d'algorithmie autour de ses équations d'ici les prochains jours.

En attendant je t'ai posé les bases de la normalisation d'un fichier de thème en définissant un schema XML, comme ça tu peux regarder comment cela est fait. Tu peux voir que le schema permet de valider la structure du fichier xml et de s'assurer que la donnée présente correspond bien à ce que l'on peut en attendre. 

Je te fais un push dans la minue :wink: Si tu as des questions ou des retours en attendant tu peux me pinger.

Pour ce qui est de l'idée de parcourir un texte par phrase, oui pourquoi pas, mais tu verras qu'avec la méthodologie appliquée dans l'équation du dessus tu n'as plus vraiment à t'en préoccuper. Un découpage par structure pourrait lui être intéressant, mais il faudrait effectuer des analyses structurelle et je pense qu'on sort du scope.

Pour l'idée de passer un document je dit oui, nous pourrions créer un objet abstrait dont ce serait le rôle, et nous pourrions lui passer des objets qui savent gérer tel ou tel type de document en paramètre.

:smile:

2020-11-26 09:59 UTC, MockingMagician commented
Bonjour @Florian-Rowehy 

Je te laisse regarder ce que j'ai mis en place, c'est certainement encore un peu brouillon mais le gros de l'idée du processus est présent.

2020-11-26 20:13 UTC, merged

2020-11-26 20:34 UTC, MockingMagician commented
Bonsoir @Florian-Rowehy 

Ayant poussé par inadvertance ton code sur la branche principale, celle-ci à été automatiquement mergé et donc fermée. Ayant poussé également du code par dessus, le revert est impossible. 

Pourrais-tu donc créer une nouvelle PR avec si possible un nom de branche différent que main, cela éviteras toute erreur de ce type. J'ai bien entendu fait disparaître tout historique de cette action dans la branche principale.

Merci